# Generated by Django 5.2.6 on 2025-09-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('published_at', models.DateTimeField(auto_created=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('full_description', models.TextField()),
                ('avatar', models.URLField()),
                ('category', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('downloads', models.IntegerField()),
                ('reviews', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('tags', models.JSONField()),
                ('features', models.JSONField()),
                ('scenarios', models.JSONField()),
            ],
        ),
    ]
